#!/bin/sh
# -*- sh -*-
# vim: ft=sh

: << =cut

=head1 NAME

clightning_info - Plugin to monitor your c-lightning node

=head1 CONFIGURATION

 [clightning_*]
    user bitcoin
    env.binary lightning-cli
    env.data_dir /var/db/c-lightning

=head1 AUTHOR

Luc Dvchosal

=head1 LICENSE

AGPLv3+

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

BINARY=${binary:-"/usr/bin/lightning-cli"}
DATA_DIR=${data_dir:-"/var/db/c-lightning"}

if [[ "$1" == test* ]]; then
    echo 
    echo "# "
    echo "# $0 $1"
    echo "# "
    echo 
fi


if [ ! -f "$BINARY" ]; then
    echo $0 $BINARY not found
    BINARY=/bin/echo
fi

if [ "$1" = "autoconf" ]; then
    autoconf="yes"

    command -v $BINARY >/dev/null || autoconf="no"

    echo $autoconf
    exit 0
fi

getinfo=$($BINARY --lightning-dir=$DATA_DIR getinfo)
getchaininfo=$($BINARY --lightning-dir=$DATA_DIR getchaininfo)


if [ "$1" = "test" ]; then

   getinfo=$(cat <<__EOF__
{
   "id": "***id***",
   "alias": "***alias***",
   "color": "cc0000",
   "num_peers": 0,
   "num_pending_channels": 0,
   "num_active_channels": 0,
   "num_inactive_channels": 0,
   "address": [
      {
         "type": "torv3",
         "address": "***toraddress***",
         "port": 1234
      }
   ],
   "binding": [
      {
         "type": "ipv4",
         "address": "127.0.0.1",
         "port": 12312
      }
   ],
   "version": "***version***",
   "blockheight": 702140,
   "network": "bitcoin",
   "msatoshi_fees_collected": 0,
   "fees_collected_msat": "0msat",
   "lightning-dir": "/var/db/c-lightning/bitcoin",
   "warning_lightningd_sync": "Still loading latest blocks from bitcoind."
}
__EOF__
)

   getchaininfo=$(cat <<__EOF__
{
   "chain": "main",
   "headercount": 737039,
   "blockcount": 737039,
   "ibd": false
}
__EOF__
)

fi


if [ "$2" = "debug" ]; then
    echo $getinfo | jq
    echo $getchaininfo | jq
fi

if [ "$1" = "config" ]; then
    echo 'graph_title c-lightning chain info'
    echo 'graph_vlabel blocks'
    echo 'graph_category clightning'
    echo 'graph_info This graph shows the info reported by lightningd.'
    echo "clightning_blockheight.label clightning blockheight ($(echo $getinfo | jq -r '.network'))'"
    echo "chain_blockcount.label bitcoin blockheight ($(echo $getchaininfo | jq -r '.chain'))'"

    exit 0
fi

echo "clightning_blockheight.value $(echo $getinfo | jq -r '.blockheight')"
echo "chain_blockcount.value $(echo $getchaininfo | jq -r '.blockcount')"
