#!/bin/sh
# -*- sh -*-
# vim: ft=sh

: << =cut

=head1 NAME

clightning_peers - Plugin to monitor your c-lightning node

=head1 CONFIGURATION

 [clightning_*]
    user bitcoin
    env.binary lightning-cli
    env.data_dir /var/db/c-lightning

=head1 AUTHOR

Luc Dvchosal

=head1 LICENSE

AGPLv3+

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

BINARY=${binary:-"/usr/bin/lightning-cli"}
DATA_DIR=${data_dir:-"/var/db/c-lightning"}

if [ "$1" == "test" ] \
   || [ "$1" == "test2" ]; then
    echo 
    echo "# "
    echo "# $0 $1"
    echo "# "
    echo 
fi



if [ ! -f "$BINARY" ]; then
    echo $0 $BINARY not found
    BINARY=/bin/echo
fi


if [ "$1" = "autoconf" ]; then
    autoconf="yes"

    command -v $BINARY >/dev/null || autoconf="no"

    echo $autoconf
    exit 0
fi

listpeers=$($BINARY --lightning-dir=$DATA_DIR listpeers)

if [ "$1" = "test" ]; then

    listpeers=$(cat <<__EOF__
{
   "peers": [
      {
         "id": "peerid100000000000000000000000000000000000000000000000000000000000",
         "connected": true,
         "netaddr": [
            "1.1.1.1:9735"
         ],
         "features": "02a2a1",
         "channels": [
            {
               "state": "CHANNELD_NORMAL",
               "scratch_txid": "scratch_txid1_00000000000000000000000000000000000000000000000000",
               "last_tx_fee_msat": 1820000,
               "feerate": {
                  "perkw": 2514,
                  "perkb": 10056
               },
               "owner": "channeld",
               "short_channel_id": "shortchanid_1",
               "direction": 1,
               "channel_id": "channelid1000000000000000000000000000000000000000000000000000000",
               "funding_txid": "fundingtxid10000000000000000000000000000000000000000000000000000",
               "close_to_addr": "bc1addr10000000000000000000000000000000000",
               "close_to": "closeto1000000000000000000000000000000000000",
               "private": false,
               "opener": "local",
               "closer": null,
               "features": [
                  "option_static_remotekey"
               ],
               "funding_allocation_msat": {
                  "peerid100000000000000000000000000000000000000000000000000000000000": 0,
                  "amount100000000000000000000000000000000000000000000000000000000000": 242557000
               },
               "funding_msat": {
                  "peerid100000000000000000000000000000000000000000000000000000000000": 0,
                  "amount100000000000000000000000000000000000000000000000000000000000": 242557000
               },
               "funding": {
                  "local_msat": 242557000,
                  "remote_msat": 0
               },
               "msatoshi_to_us": 242557000,
               "to_us_msat": 242557000,
               "min_to_us_msat": 242557000,
               "max_to_us_msat": 242557000,
               "total_msat": 242557000,
               "fee_base_msat": 1000,
               "fee_proportional_millionths": 10,
               "dust_limit_msat": 546000,
               "max_htlc_value_in_flight_msat": 18446744073709551615,
               "max_total_htlc_in_msat": 18446744073709551615,
               "their_reserve_msat": 2425000,
               "our_reserve_msat": 2425000,
               "spendable_msat": 234763000,
               "receivable_msat": 0,
               "htlc_minimum_msat": 0,
               "minimum_htlc_in_msat": 0,
               "their_to_self_delay": 144,
               "our_to_self_delay": 144,
               "max_accepted_htlcs": 30,
               "state_changes": [
                  {
                     "timestamp": "2021-08-06T20:43:55.242Z",
                     "old_state": "CHANNELD_AWAITING_LOCKIN",
                     "new_state": "CHANNELD_NORMAL",
                     "cause": "user",
                     "message": "Lockin complete"
                  }
               ],
               "status": [
                  "CHANNELD_NORMAL:Reconnected, and reestablished.",
                  "CHANNELD_NORMAL:Funding transaction locked. Channel announced."
               ],
               "in_payments_offered": 0,
               "in_offered_msat": 0,
               "in_payments_fulfilled": 0,
               "in_msatoshi_fulfilled": 0,
               "in_fulfilled_msat": 0,
               "out_payments_offered": 74,
               "out_msatoshi_offered": 10159164691,
               "out_offered_msat": 10159164691,
               "out_payments_fulfilled": 0,
               "out_msatoshi_fulfilled": 0,
               "out_fulfilled_msat": 0,
               "htlcs": []
            }
         ]
      },
      {
         "id": "peerid200000000000000000000000000000000000000000000000000000000000",
         "connected": true,
         "netaddr": [
            "127.0.0.1:63672"
         ],
         "features": "8peerid100000000000000000000000000000000000000000000000000000000000peerid100000000000000000000000000000000000000000000000000000000000peerid100000000000000000000000000000000000000000000000000000000000peerid100000000000000000000000000000000000000000000000000000000000peerid100000000000000000000000000000000000000000000000000000000000peerid100000000000000000000000000000000000000000000000000000000000peerid10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000808a52a1",
         "channels": [
            {
               "state": "CHANNELD_NORMAL",
               "scratch_txid": "scratch_txid1_00000000000000000000000000000000000000000000000000",
               "last_tx_fee": 1821000,
               "last_tx_fee_msat": 1821000,
               "feerate": {
                  "perkw": 2514,
                  "perkb": 10056
               },
               "owner": "channeld",
               "short_channel_id": "695394x571x1",
               "direction": 0,
               "channel_id": "channelid2000000000000000000000000000000000000000000000000000000",
               "funding_txid": "fundingtxid20000000000000000000000000000000000000000000000000000",
               "close_to_addr": "bc1closetoaddr0000000000000000000000000000",
               "close_to": "close_to000000000000000000000000000000000000",
               "private": false,
               "opener": "local",
               "closer": null,
               "features": [
                  "option_static_remotekey"
               ],
               "funding_allocation_msat": {
                  "peerid200000000000000000000000000000000000000000000000000000000000": 0,
                  "amount100000000000000000000000000000000000000000000000000000000000": 300000000
               },
               "funding_msat": {
                  "peerid200000000000000000000000000000000000000000000000000000000000": 0,
                  "amount100000000000000000000000000000000000000000000000000000000000": 300000000
               },
               "funding": {
                  "local_msat": 300000000,
                  "remote_msat": 0
               },
               "msatoshi_to_us": 43581601,
               "to_us_msat": 43581601,
               "msatoshi_to_us_min": 42170602,
               "min_to_us_msat": 42170602,
               "msatoshi_to_us_max": 300000000,
               "max_to_us_msat": 300000000,
               "msatoshi_total": 300000000,
               "total_msat": 300000000,
               "fee_base_msat": 1000,
               "fee_proportional_millionths": 10,
               "dust_limit_satoshis": 546,
               "dust_limit_msat": 546000,
               "max_htlc_value_in_flight_msat": 18446744073709551615,
               "max_total_htlc_in_msat": 18446744073709551615,
               "their_channel_reserve_satoshis": 3000,
               "their_reserve_msat": 3000000,
               "our_channel_reserve_satoshis": 3000,
               "our_reserve_msat": 3000000,
               "spendable_msatoshi": 35212601,
               "spendable_msat": 35212601,
               "receivable_msatoshi": 253418399,
               "receivable_msat": 253418399,
               "htlc_minimum_msat": 0,
               "minimum_htlc_in_msat": 0,
               "their_to_self_delay": 144,
               "our_to_self_delay": 144,
               "max_accepted_htlcs": 30,
               "state_changes": [
                  {
                     "timestamp": "2021-08-12T09:51:46.569Z",
                     "old_state": "CHANNELD_AWAITING_LOCKIN",
                     "new_state": "CHANNELD_NORMAL",
                     "cause": "user",
                     "message": "Lockin complete"
                  }
               ],
               "status": [
                  "CHANNELD_NORMAL:Reconnected, and reestablished.",
                  "CHANNELD_NORMAL:Funding transaction locked. Channel announced."
               ],
               "in_payments_offered": 62,
               "in_msatoshi_offered": 7734200500,
               "in_offered_msat": 7734200500,
               "in_payments_fulfilled": 11,
               "in_msatoshi_fulfilled": 2612000,
               "in_fulfilled_msat": 2612000,
               "out_payments_offered": 6,
               "out_msatoshi_offered": 259030399,
               "out_offered_msat": 259030399,
               "out_payments_fulfilled": 6,
               "out_msatoshi_fulfilled": 259030399,
               "out_fulfilled_msat": 259030399,
               "htlcs": []
            }
         ]
      },
      {
         "id": "peerid300000000000000000000000000000000000000000000000000000000000",
         "connected": true,
         "netaddr": [
            "127.0.0.1:64890"
         ],
         "features": "8peerid100000000000000000000000000000000000000000000000000000000000peerid100000000000000000000000000000000000000000000000000000000000peerid100000000000000000000000000000000000000000000000000000000000peerid100000000000000000000000000000000000000000000000000000000000peerid100000000000000000000000000000000000000000000000000000000000peerid100000000000000000000000000000000000000000000000000000000000peerid10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000808252a1",
         "channels": []
      }
   ]
}
__EOF__
)

fi

if [ "$1" = "test2" ]; then

    listpeers=$(cat <<__EOF__
{
   "peers": []
}
__EOF__
)

fi


#
# transform
#

jsont=$(cat <<__EOF__
{
   "total": [
      [ 0, .peers[].channels[].total_msat 
      ] 
      | add 
      / 1000 
   ][0],

   "peers": [ 
      .peers[] | {
         "id": .id,
         "label": .netaddr[0],
         "value":[ 
            [ 
               0, 
               .channels[].total_msat  
            ] 
            | add 
            / 1000 
         ][0]
      }],

}
__EOF__
)
result=$(echo $listpeers | jq "$(echo $jsont)")
if [ "$1" = "debug" ]; then
    echo $listpeers | jq
    echo $result | jq
fi


#
# config
#

if [ "$1" = "config" ]; then

    echo 'graph_title c-lightning peers info'
    echo 'graph_vlabel peers'
    echo 'graph_category clightning'
    echo 'graph_info This graph shows the peers reported by lightningd.'

    echo 'total.label total'

    for item in $(echo $result | jq -c '.peers[]'); do
        id=$(echo $item | jq -r ".id")
        label=$(echo $item | jq -r ".label")
        value=$(echo $item | jq -r ".value * -1")
        sid=$(echo $id | sha1sum | cut -c1-8)
        echo "peer_$sid.label $label"
        echo "peer_$sid.draw AREASTACK"
    done

    exit 0
fi

echo "total.value $(echo $result | jq -r '.total')"

for item in $(echo $result | jq -c '.peers[]'); do
   id=$(echo $item | jq -r ".id")
   label=$(echo $item | jq -r ".label")
   value=$(echo $item | jq -r ".value")
   echo "peer_$(echo $id | sha1sum | cut -c1-8).value $value"
done
