#!/bin/sh
# -*- sh -*-
# vim: ft=sh

: << =cut

=head1 NAME

clightning_forwards_amount - Plugin to monitor your forwards on the lightning network

=head1 CONFIGURATION

 [clightning_*]
    user bitcoin
    env.binary lightning-cli
    env.data_dir /var/db/c-lightning

=head1 AUTHOR

Luc Dvchosal

=head1 LICENSE

AGPLv3+

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

BINARY=${binary:-"/usr/bin/lightning-cli"}
DATA_DIR=${data_dir:-"/var/db/c-lightning"}

if [ "$1" == "test" ] \
   || [ "$1" == "test2" ]; then
    echo 
    echo "# "
    echo "# $0 $1"
    echo "# "
    echo 
fi



if [ ! -f "$BINARY" ]; then
    echo $0 $BINARY not found
    BINARY=/bin/echo
fi


if [ "$1" = "autoconf" ]; then
    autoconf="yes"

    command -v $BINARY >/dev/null || autoconf="no"

    echo $autoconf
    exit 0
fi

listforwards=$($BINARY --lightning-dir=$DATA_DIR listforwards)

if [ "$1" = "test" ]; then

   listforwards=$(cat <<__EOF__
{
   "forwards": [
      {
         "in_channel": "694360x1604x1",
         "out_channel": "694393x176x1",
         "in_msatoshi": 1000,
         "in_msat": "1000msat",
         "out_msatoshi": 1000,
         "out_msat": "1000msat",
         "fee": 6000,
         "fee_msat": "6000msat",
         "status": "settled",
         "received_time": 1628388383.738,
         "resolved_time": 1628388386.077
      },
      {
         "in_channel": "694360x1604x1",
         "out_channel": "694393x176x1",
         "in_msatoshi": 500006000,
         "in_msat": "500006000msat",
         "out_msatoshi": 500000000,
         "out_msat": "500000000msat",
         "fee": 6000,
         "fee_msat": "6000msat",
         "status": "failed",
         "received_time": 1628388383.738,
         "resolved_time": 1628388386.077
      },
      {
         "in_channel": "694360x1604x1",
         "out_channel": "694393x176x1",
         "in_msatoshi": 500006000,
         "in_msat": "500006000msat",
         "out_msatoshi": 500000000,
         "out_msat": "500000000msat",
         "fee": 6000,
         "fee_msat": "6000msat",
         "status": "local_failed",
         "received_time": 1628388383.738,
         "resolved_time": 1628388386.077
      },
      {
         "in_channel": "694360x1604x1",
         "in_msatoshi": 500006000,
         "in_msat": "500006000msat",
         "fee": 6000,
         "fee_msat": "6000msat",
         "status": "local_failed",
         "received_time": 1628388383.738,
         "resolved_time": 1628388386.077
      },
      {
         "out_channel": "694393x176x1",
         "out_msatoshi": 500000000,
         "out_msat": "500000000msat",
         "fee": 6000,
         "fee_msat": "6000msat",
         "status": "local_failed",
         "received_time": 1628388383.738,
         "resolved_time": 1628388386.077
      }
   ]
}
__EOF__
)

fi

if [ "$1" = "test2" ]; then

   listforwards=$(cat <<__EOF__
{
   "forwards": []
}
__EOF__
)

fi

jsont=$(cat <<__EOF__
{

   "in": [
      [
         [ .forwards[] | .in_msatoshi ], 
         [0]
      ]
      | add
      | add
      / 1000 
   ] [0],

   "out": [
      [
         [ .forwards[] | .out_msatoshi ], 
         [0]
      ]
      | add
      | add
      / 1000 
   ] [0]

}
__EOF__
)

result=$(echo $listforwards | jq "$(echo $jsont)")

if [ "$2" = "debug" ]; then
    echo $listforwards | jq
    echo $result | jq
fi

if [ "$1" = "config" ]; then
    echo 'graph_title Forwards amounts'
    echo 'graph_vlabel sats'
    echo 'graph_category clightning'
    echo 'graph_info This graph shows the forwards on your clightning node.'
    
    echo 'in.label in'
    echo 'out.label out'

    exit 0
fi

echo "in.value $(echo $result | jq -r '.in')"
echo "out.value -$(echo $result | jq -r '.out')"
