#!/bin/sh
# -*- sh -*-
# vim: ft=sh

: << =cut

=head1 NAME

clightning_funds - Plugin to monitor your funds (channels and funds) on the lightning network

=head1 CONFIGURATION

 [clightning_*]
    user bitcoin
    env.binary lightning-cli
    env.data_dir /var/db/c-lightning

=head1 AUTHOR

Luc Dvchosal

=head1 LICENSE

AGPLv3+

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

BINARY=${binary:-"/usr/bin/lightning-cli"}
DATA_DIR=${data_dir:-"/var/db/c-lightning"}

if [ "$1" = "autoconf" ]; then
    autoconf="yes"

    command -v $BINARY >/dev/null || autoconf="no"

    echo $autoconf
    exit 0
fi

listfunds=$($BINARY --lightning-dir=$DATA_DIR listfunds)

# lightning-cli --lightning-dir=/var/db/c-lightning listfunds
# {
#    "outputs": [
#       {  
#          "txid": "***txid***",
#          "output": 0,
#          "value": 123456,
#          "amount_msat": "123456000msat",
#          "scriptpubkey": "***scriptpubkey***",
#          "address": "***address**",
#          "status": "confirmed",
#          "blockheight": 695394,
#          "reserved": false
#       },
#       ...
#    ],
#    "channels": [
#       {
#          "peer_id": "***peer_id***",
#          "connected": true,
#          "state": "CHANNELD_NORMAL",
#          "short_channel_id": "***short_channel_id***",
#          "channel_sat": 123123,
#          "our_amount_msat": "123123000msat",
#          "channel_total_sat": 123123,
#          "amount_msat": "123123000msat",
#          "funding_txid": "***funding_txid***",
#          "funding_output": 1
#       },
#       ...
#    ]
# }


jsont=$(cat <<__EOF__

{
   "total_funds": 
      [ 
         [ 
            "0", 
            .channels[].amount_msat, 
            .outputs[].amount_msat
               | sub("msat";"")  
               | tonumber 
         ] 
         | add 
         / 1000 
      ][0],

   "total_channels":
      [ 
         [ 
            "0", 
            .channels[].amount_msat  
               | sub("msat";"")  
               | tonumber 
         ] 
         | add 
         / 1000 
      ][0],

   "total_outpouts":
      [ 
         [ 
            "0", 
            .outputs[].amount_msat  
               | sub("msat";"")  
               | tonumber 
         ] 
         | add 
         / 1000 
      ][0],

   "channels": [ 
      .channels[] | {
         "id": .peer_id,
         "label": .short_channel_id,
         "value": [ 
            .amount_msat 
               | sub("msat";"") 
               | tonumber 
               / 1000 
            ][0]
      }],

   "outputs": [ .outputs[] | {
         "id": .txid,
         "label": .address,
         "value": [ 
            .amount_msat 
               | sub("msat";"") 
               | tonumber 
               / 1000
         ][0]
      }]
}
__EOF__
)

result=$(echo $listfunds | jq "$(echo $jsont)")

# echo $result | jq
# 
# {
#   "txids": [
#     "***txid1***",
#     "***txid2***"
#   ],
#   "peer_ids": [
#     "***peer_id1***",
#     "***peer_id2***"
#   ],
#   "total_funds": 580245,
#   "total_channels": 333333,
#   "total_outpouts": 246912,
#   "channels": [
#     {
#       "peer_id": "***peer_id1***",
#       "amount_msat": 222222
#     },
#     {
#       "peer_id": "***peer_id2***",
#       "amount_msat": 111111
#     }
#   ],
#   "outputs": [
#     {
#       "txid": "***txid1***",
#       "amount_msat": 123456
#     },
#     {
#       "txid": "***txid2***",
#       "amount_msat": 123456
#     }
#   ]
# }


if [ "$1" = "config" ]; then
    echo 'graph_title Channel and funds'
    echo 'graph_vlabel sats'
    echo 'graph_category clightning'
    echo 'graph_info This graph shows the sats available on open channels and remaining funds.'
    echo 'total.label total'
    echo 'outputs.label outputs'
    echo 'channels.label channels'

   for item in $(echo $result | jq -c '.outputs[]'); do
      id=$(echo $item | jq ".id")
      label=$(echo $item | jq ".label")
      value=$(echo $item | jq ".value * -1")
      echo "output_$(echo $id | sha1sum | cut -c1-8).label out ${label}"
   done

   for item in $(echo $result | jq -c '.channels[]'); do
      id=$(echo $item | jq ".id")
      label=$(echo $item | jq ".label")
      value=$(echo $item | jq ".value")
      echo "peer_$(echo $peerid | sha1sum | cut -c1-8).label chan ${label}"
   done

    exit 0
fi

echo "total.value $(echo $result | jq '.total_funds')"
echo "outputs.value $(echo $result | jq '.total_outpouts')"
echo "channels.value $(echo $result | jq '.total_channels')"

for item in $(echo $result | jq -c '.outputs[]'); do
   id=$(echo $item | jq ".id")
   label=$(echo $item | jq ".label")
   value=$(echo $item | jq ".value * -1")
   echo "output_$(echo $id | sha1sum | cut -c1-8).value $value"
done

for item in $(echo $result | jq -c '.channels[]'); do
   id=$(echo $item | jq ".id")
   label=$(echo $item | jq ".label")
   value=$(echo $item | jq ".value")
   echo "peer_$(echo $id | sha1sum | cut -c1-8).value $value"
done
