#!/bin/sh
# -*- sh -*-
# vim: ft=sh

: << =cut

=head1 NAME

clightning_channels - Plugin to monitor your channels on the lightning network

=head1 CONFIGURATION

 [clightning_*]
    user bitcoin
    env.binary lightning-cli
    env.data_dir /var/db/c-lightning

=head1 AUTHOR

Luc Dvchosal

=head1 LICENSE

AGPLv3+

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

BINARY=${binary:-"/usr/bin/lightning-cli"}
DATA_DIR=${data_dir:-"/var/db/c-lightning"}

if [ "$1" == "test" ] \
   || [ "$1" == "test2" ]; then
    echo 
    echo "# "
    echo "# $0 $1"
    echo "# "
    echo 
fi


if [ ! -f "$BINARY" ]; then
    echo $0 $BINARY not found
    BINARY=/bin/echo
fi

if [ "$1" = "autoconf" ]; then
    autoconf="yes"

    command -v $BINARY >/dev/null || autoconf="no"

    echo $autoconf
    exit 0
fi

if [ "$1" = "debug" ]; then
    echo $listfunds | jq
fi

listfunds=$($BINARY --lightning-dir=$DATA_DIR listfunds)

if [ "$1" = "test" ]; then

   listfunds=$(cat <<__EOF__
{                                                                                                                                                                                        
   "outputs": [                                                                                                                                                                          
      {                                                                                                                                                                                  
         "txid": "***txid1***",                                                                                                     
         "output": 0,                                                                                                                                                                    
         "value": 123456,
         "amount_msat": 123456000,
         "scriptpubkey": "***scriptpubkey***",
         "address": "***address**",
         "status": "confirmed",
         "blockheight": 695394,
         "reserved": false
      },                                                                                                                                                                          
      {                                                                                                                                                                                  
         "txid": "***txid2***",                                                                                                     
         "output": 0,                                                                                                                                                                    
         "value": 123456,
         "amount_msat": 123456000,
         "scriptpubkey": "***scriptpubkey***",
         "address": "***address**",
         "status": "confirmed",
         "blockheight": 695394,
         "reserved": false
      }
   ],
   "channels": [
      {
         "peer_id": "***peer_id1***",
         "connected": true,
         "state": "CHANNELD_NORMAL",
         "short_channel_id": "***short_channel_id1**",
         "our_amount_msat": 222222000,
         "amount_msat": 222222000,
         "funding_txid": "***funding_txid***",
         "funding_output": 1
      },
      {
         "peer_id": "***peer_id2***",
         "connected": true,
         "state": "CHANNELD_NORMAL",
         "short_channel_id": "***short_channel_id2**",
         "our_amount_msat": 1111111000,
         "amount_msat": 111111000,
         "funding_txid": "***funding_txid***",
         "funding_output": 1
      }
   ]
}
__EOF__
)

fi

if [ "$1" = "test2" ]; then

   listfunds=$(cat <<__EOF__
{
   "outputs": [ ],
   "channels": [ ]
}
__EOF__
)

fi

#
# transform
#

jsont=$(cat <<__EOF__
{
   "channels" : {
      "total": .channels | length,
      "short_channel_id": [ .channels[] | .short_channel_id ]
   },

   "balance" : [
      .channels[] |
      {
         "short_channel_id" : .short_channel_id,
         "our" : .our_amount_msat,
         "their" : ( .our_amount_msat - .amount_msat )
      }
   ]
}
__EOF__
)

result=$(echo $listfunds | jq "$(echo $jsont)")

if [ "$2" = "debug" ]; then
   cat <<__EOF__

#
# listfunds
#

__EOF__

echo $listfunds | jq

   cat <<__EOF__

#
# result
#

__EOF__

echo $result | jq

fi

#
# config
#

if [ "$1" = "config" ]; then

   cat <<__EOF__
multigraph channels

graph_title Channel count
graph_vlabel number of channels
graph_category clightning
graph_info This graph shows the number of open channels.
total.label total
total.draw LINE3

__EOF__

   for short_channel_id in $(echo $result | jq -r '.channels.short_channel_id[]'); do
      sid=$(echo $short_channel_id | sha1sum | cut -c1-8)
      echo "channel_$sid.label $short_channel_id"
      echo "channel_$sid.draw AREASTACK"
   done

   for channel in $(echo $result | jq -c -r '.balance[]'); do
      short_channel_id=$(echo $channel | jq -r '.short_channel_id')
      label=$(echo $short_channel_id | sha1sum | cut -c1-8)

      cat <<__EOF__
      
multigraph channels_balance_$label

graph_title channel balance $short_channel_id
graph_vlabel sats
graph_category clightning
graph_info This graph shows the balance of $short_channel_id.

our.label our
our.draw AREA
their.label their
their.draw AREA

__EOF__

   done

   exit 0
fi


#
# run
#


cat <<__EOF__
multigraph channels

total.value $(echo $result | jq -r '.channels.total')
__EOF__

for short_channel_id in $(echo $result | jq -r '.channels.short_channel_id[]'); do
   sid=$(echo $short_channel_id | sha1sum | cut -c1-8)
   echo "channel_$sid.value 1"
done


for balance in $(echo $result | jq -c -r '.balance[]'); do
   short_channel_id=$(echo $balance | jq -r '.short_channel_id')
   our=$(echo $balance | jq -r '.our')
   their=$(echo $balance | jq -r '.their')
   label=$(echo $short_channel_id | sha1sum | cut -c1-8)

   cat <<__EOF__

multigraph channels_balance_$label

our.value $our
their.value $their
__EOF__

done
