#!/bin/sh
# -*- sh -*-
# vim: ft=sh

: << =cut

=head1 NAME

clightning_feerates_perkw - Plugin to monitor your c-lightning node

=head1 CONFIGURATION

 [clightning_*]
    user bitcoin
    env.binary lightning-cli
    env.data_dir /var/db/c-lightning

=head1 AUTHOR

Luc Dvchosal

=head1 LICENSE

AGPLv3+

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

BINARY=${binary:-"/usr/bin/lightning-cli"}
DATA_DIR=${data_dir:-"/var/db/c-lightning"}

if [ "$1" == "test" ] \
   || [ "$1" == "test2" ]; then
    echo 
    echo "# "
    echo "# $0 $1"
    echo "# "
    echo 
fi


if [ ! -f "$BINARY" ]; then
    echo $0 $BINARY not found
    BINARY=/bin/echo
fi


if [ "$1" = "autoconf" ]; then
    autoconf="yes"

    command -v $BINARY >/dev/null || autoconf="no"

    echo $autoconf
    exit 0
fi

feerates=$($BINARY --lightning-dir=$DATA_DIR feerates perkw)

if [ "$1" == "test" ] \
   || [ "$1" == "test2" ]; then

   feerates=$(cat <<__EOF__
{
   "perkw": {
      "opening": 485,
      "mutual_close": 253,
      "unilateral_close": 640,
      "delayed_to_us": 485,
      "htlc_resolution": 640,
      "penalty": 485,
      "min_acceptable": 253,
      "max_acceptable": 35538
   },
   "onchain_fee_estimates": {
      "opening_channel_satoshis": 340,
      "mutual_close_satoshis": 170,
      "unilateral_close_satoshis": 382,
      "htlc_timeout_satoshis": 424,
      "htlc_success_satoshis": 449
   }
}
__EOF__
)

fi


if [ "$2" = "debug" ]; then
    echo $getlog | jq
fi

if [ "$1" = "config" ]; then
    echo 'graph_title c-lightning feerates perkw'
    echo 'graph_vlabel sats'
    echo 'graph_category clightning'
    echo 'graph_info This graph shows the feerates perkw reported by lightningd.'

    echo "perkw_opening.label opening"
    echo "perkw_mutual_close.label mutual_close"
    echo "perkw_unilateral_close.label unilateral_close"
    echo "perkw_delayed_to_us.label delayed_to_us"
    echo "perkw_htlc_resolution.label htlc_resolution"
    echo "perkw_penalty.label penalty"
    echo "perkw_min_acceptable.label min_acceptable"
    echo "perkw_max_acceptable.label max_acceptable"
    
    echo "onchain_opening.label onchain_opening"
    echo "onchain_mutual_close.label onchain_mutual_close"
    echo "onchain_unilateral_close.label onchain_unilateral_close"
    echo "onchain_htlc_timeout.label onchain_htlc_timeout"
    echo "onchain_htlc_success.label onchain_htlc_success"

    exit 0
fi


echo "perkw_opening.value $(echo $feerates | jq -r '.perkw.opening')"
echo "perkw_mutual_close.value $(echo $feerates | jq -r '.perkw.mutual_close')"
echo "perkw_unilateral_close.value $(echo $feerates | jq -r '.perkw.unilateral_close')"
echo "perkw_delayed_to_us.value $(echo $feerates | jq -r '.perkw.delayed_to_us')"
echo "perkw_htlc_resolution.value $(echo $feerates | jq -r '.perkw.htlc_resolution')"
echo "perkw_penalty.value $(echo $feerates | jq -r '.perkw.penalty')"
echo "perkw_min_acceptable.value $(echo $feerates | jq -r '.perkw.min_acceptable')"
echo "perkw_max_acceptable.value $(echo $feerates | jq -r '.perkw.max_acceptable')"

echo "onchain_opening.value $(echo $feerates | jq -r '.onchain_fee_estimates.opening_channel_satoshis')"
echo "onchain_mutual_close.value $(echo $feerates | jq -r '.onchain_fee_estimates.mutual_close_satoshis')"
echo "onchain_unilateral_close.value $(echo $feerates | jq -r '.onchain_fee_estimates.unilateral_close_satoshis')"
echo "onchain_htlc_timeout.value $(echo $feerates | jq -r '.onchain_fee_estimates.htlc_timeout_satoshis')"
echo "onchain_htlc_success.value $(echo $feerates | jq -r '.onchain_fee_estimates.htlc_success_satoshis')"
