#!/bin/sh
# -*- sh -*-
# vim: ft=sh

: << =cut

=head1 NAME

clightning_forwards - Plugin to monitor your forwards on the lightning network

=head1 CONFIGURATION

 [clightning_*]
    user bitcoin
    env.binary lightning-cli
    env.data_dir /var/db/c-lightning

=head1 AUTHOR

Luc Dvchosal

=head1 LICENSE

AGPLv3+

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

BINARY=${binary:-"/usr/bin/lightning-cli"}
DATA_DIR=${data_dir:-"/var/db/c-lightning"}

if [ "$1" == "test" ] \
   || [ "$1" == "test2" ]; then
    echo 
    echo "# "
    echo "# $0 $1"
    echo "# "
    echo 
fi



if [ ! -f "$BINARY" ]; then
    echo $0 $BINARY not found
    BINARY=/bin/echo
fi


if [ "$1" = "autoconf" ]; then
    autoconf="yes"

    command -v $BINARY >/dev/null || autoconf="no"

    echo $autoconf
    exit 0
fi

listforwards=$($BINARY --lightning-dir=$DATA_DIR listforwards)

if [ "$1" = "test" ]; then

   listforwards=$(cat <<__EOF__
{
   "forwards": [
      {
         "in_channel": "694360x1604x1",
         "out_channel": "694393x176x1",
         "in_msat": 1000,
         "out_msat": 1000,
         "fee_msat": 6000,
         "status": "settled",
         "received_time": 1628388383.738,
         "resolved_time": 1628388386.077
      },
      {
         "in_channel": "694360x1604x1",
         "out_channel": "694393x176x1",
         "in_msat": 500006000,
         "out_msat": 500000000,
         "fee_msat": 6000,
         "status": "failed",
         "received_time": 1628388383.738,
         "resolved_time": 1628388386.077
      },
      {
         "in_channel": "694360x1604x1",
         "out_channel": "694393x176x1",
         "in_msat": 500006000,
         "out_msat": 500000000,
         "fee_msat": 6000,
         "status": "local_failed",
         "received_time": 1628388383.738,
         "resolved_time": 1628388386.077
      },
      {
         "in_channel": "694360x1604x1",
         "in_msat": 500006000,
         "fee_msat": 6000,
         "status": "local_failed",
         "received_time": 1628388383.738,
         "resolved_time": 1628388386.077
      },
      {
         "out_channel": "694393x176x1",
         "out_msat": 500000000,
         "fee_msat": 6000,
         "status": "local_failed",
         "received_time": 1628388383.738,
         "resolved_time": 1628388386.077
      }
   ]
}
__EOF__
)

fi

if [ "$1" = "test2" ]; then

   listforwards=$(cat <<__EOF__
{
   "forwards": []
}
__EOF__
)

fi


#
# transform
#

jsont=$(cat <<__EOF__
{
   "forwards" : {
      "total": [ 
         .forwards[] 
      ] 
      | length,

      "settled": [
         .forwards[] 
            | select(.status == "settled") 
      ] 
      | length,

      "failed": [ 
         .forwards[] 
            | select(.status == "failed") 
      ] 
      | length,

      "local_failed": [ 
         .forwards[] 
            | select(.status == "local_failed") 
      ] 
      | length
   },
   "amount" : {

      "in": [
         [ 
            .forwards[] 
               | select(.in_msat)
               | .in_msat
               / 1000
         ], 
         [0]
      ]
      | add
      | add,

      "out": [
         [ 
            .forwards[] 
               | select(.out_msat)
               | .out_msat
               / 1000
         ], 
         [0]
      ]
      | add
      | add,
   },

   "fees" : {
      
      "total": [
         [ 
            .forwards[] 
               | select(.fee_msat)
               | .fee_msat 
         ], 
         [0]
      ] 
      | add 
      | add,

      "settled": [
         [ 
            .forwards[] 
               | select(.status == "settled")
               | select(.fee_msat)
               | .fee_msat 
         ], [0]
      ] 
      | add 
      | add,

      "failed": [
         [ 
            .forwards[] 
               | select(.status == "failed")
               | select(.fee_msat)
               | .fee_msat 
         ], [0]
      ] 
      | add 
      | add

      
   }
}
__EOF__
)

result=$(echo $listforwards | jq "$(echo $jsont)")

if [ "$1" = "debug" ] || [ "$2" = "debug" ]; then
    echo $listforwards | jq
    echo $result | jq
fi


#
# config
#

if [ "$1" = "config" ]; then
   cat <<__EOF__
multigraph forwards

graph_title Forwards
graph_vlabel forwards
graph_category clightning
graph_info This graph shows the forwards on your clightning node

total.label total
settled.label settled
failed.label failed
local_failed.label local_failed'

multigraph forwards_amount

graph_title Forwards amounts
graph_vlabel sats
graph_category clightning
graph_info This graph shows the forwards on your clightning node

in.label in
out.label out'

multigraph forwards_fees

graph_title Forwards fees
graph_vlabel msats
graph_category clightning
graph_info This graph shows the forwards fees on your clightning node.

total.label total
settled.label settled
failed.label failed'

__EOF__

    exit 0
fi

   cat <<__EOF__
multigraph forwards

total.value $(echo $result | jq -r '.forwards.total')
settled.value $(echo $result | jq -r '.forwards.settled')
failed.value $(echo $result | jq -r '.forwards.failed')
local_failed.value $(echo $result | jq -r '.forwards.local_failed')

multigraph forwards_amount

in.value $(echo $result | jq -r '.amount.in')
out.value -$(echo $result | jq -r '.amount.out')

multigraph forwards_fees

total.value $(echo $result | jq -r '.fees.total')
settled.value $(echo $result | jq -r '.fees.settled')
failed.value $(echo $result | jq -r '.fees.failed')

__EOF__
