#!/bin/sh
# -*- sh -*-
# vim: ft=sh

# lightning-cli --lightning-dir=/var/db/c-lightning listfunds

listfunds=$(cat <<__EOF__
{                                                                                                                                                                                        
   "outputs": [                                                                                                                                                                          
      {                                                                                                                                                                                  
         "txid": "***txid1***",                                                                                                     
         "output": 0,                                                                                                                                                                    
         "value": 123456,
         "amount_msat": "123456000msat",
         "scriptpubkey": "***scriptpubkey***",
         "address": "***address**",
         "status": "confirmed",
         "blockheight": 695394,
         "reserved": false
      },                                                                                                                                                                          
      {                                                                                                                                                                                  
         "txid": "***txid2***",                                                                                                     
         "output": 0,                                                                                                                                                                    
         "value": 123456,
         "amount_msat": "123456000msat",
         "scriptpubkey": "***scriptpubkey***",
         "address": "***address**",
         "status": "confirmed",
         "blockheight": 695394,
         "reserved": false
      }
   ],
   "channels": [
      {
         "peer_id": "***peer_id1***",
         "connected": true,
         "state": "CHANNELD_NORMAL",
         "short_channel_id": "***short_channel_id***",
         "channel_sat": 222222,
         "our_amount_msat": "222222000msat",
         "channel_total_sat": 222222,
         "amount_msat": "222222000msat",
         "funding_txid": "***funding_txid***",
         "funding_output": 1
      },
      {
         "peer_id": "***peer_id2***",
         "connected": true,
         "state": "CHANNELD_NORMAL",
         "short_channel_id": "***short_channel_id***",
         "channel_sat": 111111,
         "our_amount_msat": "1111111000msat",
         "channel_total_sat": 1111111,
         "amount_msat": "111111000msat",
         "funding_txid": "***funding_txid***",
         "funding_output": 1
      }
   ]
}
__EOF__
)

# read -r -d '' listfunds <<__EOF__
# {
#    "outputs": [ ],
#    "channels": [ ]
# }
# __EOF__

jsont=$(cat <<__EOF__
{
   "txids": [
      .outputs[].txid
   ],

   "peer_ids": [
      .channels[].peer_id
   ],

   "total_funds": 
      [ 
         [ 
            "0", 
            .channels[].amount_msat, 
            .outputs[].amount_msat
               | sub("msat";"")  
               | tonumber 
         ] 
         | add 
         / 1000 
      ][0],

   "total_channels":
      [ 
         [ 
            "0", 
            .channels[].amount_msat  
               | sub("msat";"")  
               | tonumber 
         ] 
         | add 
         / 1000 
      ][0],

   "total_outpouts":
      [ 
         [ 
            "0", 
            .outputs[].amount_msat  
               | sub("msat";"")  
               | tonumber 
         ] 
         | add 
         / 1000 
      ][0],

   "channels": [ 
      .channels[] | {
         "peer_id": .peer_id,
         "amount_msat": [ 
            .amount_msat 
               | sub("msat";"") 
               | tonumber 
               / 1000 
            ][0]
      }],

   "outputs": [ .outputs[] | {
         "txid": .txid,
         "amount_msat": [ 
            .amount_msat 
               | sub("msat";"") 
               | tonumber 
               / 1000
         ][0]
      }]
      
   
}
__EOF__
)

echo $listfunds | jq
result=$(echo $listfunds | jq "$(echo $jsont)")
echo $result | jq


echo 'total.label total (sat)'
echo 'outputs.label outputs (sat)'
echo 'channels.label channels (sat)'

for txid in $(echo $result | jq '.txids[]'); do
    echo "output_$(echo $txid | sha1sum | cut -c1-8).label ${txid}"
done

for peerid in $(echo $result | jq '.peer_ids[]'); do
    echo "peer_$(echo $peerid | sha1sum | cut -c1-8).label ${peerid}"
done

echo "total.value $(echo $result | jq '.total_funds')"
echo "outputs.value $(echo $result | jq '.total_outpouts')"
echo "channels.value $(echo $result | jq '.total_channels')"

for output in $(echo $result | jq -c '.outputs[]'); do
   id=$(echo $output | jq ".txid")
   value=$(echo $output | jq ".amount_msat * -1")
   echo "output_$(echo $id | sha1sum | cut -c1-8).value $value"
done

for channel in $(echo $result | jq -c '.channels[]'); do
   id=$(echo $channel | jq ".peer_id")
   value=$(echo $channel | jq ".amount_msat")
   echo "peer_$(echo $id | sha1sum | cut -c1-8).value $value"
done
